### ISSUE TITLE
Using the old http method to get a queue

### ISSUE THREAD

**Issue by Rirusha** [SFmindMAP/Ya.music-bio-status-telegram#1]
Hello.

All queues* http methods are depricated and used only by old official Windows client and unofficial clients.

**Comment by SFmindMAP** [comment]
fixed but not for web
![image](https://github.com/SFmindMAP/Ya.music-bio-status-telegram/assets/138624372/bd3e70cf-8100-4a45-8700-29cbba49640d)

**Comment by Sleryfink** [comment]
fixed, unstable beta method for the new version of ya. music (windows version is not supported)
![photo_2024-06-03_22-21-45](https://github.com/SFmindMAP/Ya.music-bio-status-telegram/assets/138624372/fe3f1fbc-9716-4d3b-bd59-4dcb1e270a5b)
